# Generated by Django 5.2 on 2026-04-19 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_create_schema'),
    ]

    operations = [
        migrations.CreateModel(
            name='EjecucionTareaProgramada',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('eliminado', models.BooleanField(default=False)),
                ('disparado_por', models.CharField(max_length=20)),
                ('estado', models.CharField(default='pendiente', max_length=20)),
                ('iniciado_en', models.DateTimeField()),
                ('finalizado_en', models.DateTimeField(blank=True, null=True)),
                ('mensaje_error', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': '[ml].[ejecucion_tarea_programada]',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LotePrediccion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('eliminado', models.BooleanField(default=False)),
                ('nombre_modelo', models.CharField(max_length=100, unique=True)),
                ('generado_en', models.DateTimeField()),
                ('cantidad_predicciones', models.IntegerField(default=0)),
                ('parametros', models.JSONField(default=dict)),
                ('estado', models.CharField(default='generando', max_length=20)),
            ],
            options={
                'db_table': '[ml].[lote_prediccion]',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TareaProgramada',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('eliminado', models.BooleanField(default=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('tipo_job', models.CharField(max_length=30)),
                ('cron_schedule', models.CharField(blank=True, max_length=50, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': '[ml].[tarea_programada]',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LogTareaProgramada',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('eliminado', models.BooleanField(default=False)),
                ('nombre_step', models.CharField(max_length=100)),
                ('orden_step', models.PositiveSmallIntegerField()),
                ('estado', models.CharField(max_length=20)),
                ('duracion_segundos', models.FloatField(blank=True, null=True)),
                ('mensaje_error', models.TextField(blank=True, null=True)),
                ('ejecutado_en', models.DateTimeField()),
                ('ejecucion_tarea_programada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_steps', to='app.ejecuciontareaprogramada')),
            ],
            options={
                'db_table': '[ml].[log_tarea_programada]',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResultadoPrediccion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('eliminado', models.BooleanField(default=False)),
                ('cliente_id', models.CharField(max_length=50)),
                ('producto_id', models.CharField(max_length=50)),
                ('fuente', models.CharField(max_length=20)),
                ('cantidad_sugerida', models.FloatField()),
                ('score', models.FloatField()),
                ('posicion', models.PositiveSmallIntegerField()),
                ('lote_prediccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='app.loteprediccion')),
            ],
            options={
                'db_table': '[ml].[resultado_prediccion]',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='ejecuciontareaprogramada',
            name='tarea_programada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ejecuciones', to='app.tareaprogramada'),
        ),
        migrations.CreateModel(
            name='VersionModelo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('eliminado', models.BooleanField(default=False)),
                ('nombre_modelo', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=50)),
                ('entrenado_en', models.DateTimeField()),
                ('ruta_pkl', models.CharField(max_length=500)),
                ('tipo_fuente_datos', models.CharField(max_length=20)),
                ('parametros', models.JSONField(default=dict)),
                ('activo', models.BooleanField(default=False)),
                ('ejecucion_tarea_programada', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='version_modelo', to='app.ejecuciontareaprogramada')),
            ],
            options={
                'db_table': '[ml].[version_modelo]',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MetricaModelo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('eliminado', models.BooleanField(default=False)),
                ('nombre_metrica', models.CharField(max_length=100)),
                ('valor_metrica', models.FloatField()),
                ('split', models.CharField(blank=True, max_length=20, null=True)),
                ('calculado_en', models.DateTimeField(auto_now_add=True)),
                ('version_modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metricas', to='app.versionmodelo')),
            ],
            options={
                'db_table': '[ml].[metrica_modelo]',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='loteprediccion',
            name='version_modelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lote_prediccion_activo', to='app.versionmodelo'),
        ),
        migrations.CreateModel(
            name='TareaParametro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('eliminado', models.BooleanField(default=False)),
                ('clave', models.CharField(max_length=100)),
                ('valor', models.CharField(max_length=500)),
                ('tipo_dato', models.CharField(default='string', max_length=20)),
                ('tarea_programada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parametros', to='app.tareaprogramada')),
            ],
            options={
                'db_table': '[ml].[tarea_parametro]',
                'abstract': False,
                'unique_together': {('tarea_programada', 'clave')},
            },
        ),
    ]
