# Generated by Django 5.2 on 2026-05-03 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_create_schema'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(default=False)),
                ('nombre_cliente', models.CharField(max_length=200)),
                ('codigo_erp', models.CharField(max_length=100)),
            ],
            options={
                'db_table': '[ml].[clientes]',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FuenteDatos',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(default=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(max_length=50)),
            ],
            options={
                'db_table': '[ml].[fuente_datos]',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LotePrediccion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(default=False)),
                ('nombre_modelo', models.CharField(max_length=100)),
                ('generado_en', models.DateTimeField()),
                ('cantidad_predicciones', models.IntegerField(default=0)),
                ('parametros', models.JSONField(default=dict)),
                ('estado', models.CharField(default='generando', max_length=20)),
            ],
            options={
                'db_table': '[ml].[lote_prediccion]',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EjecucionTareaProgramada',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(default=False)),
                ('disparado_por', models.CharField(max_length=20)),
                ('estado', models.CharField(default='pendiente', max_length=20)),
                ('numero_intento', models.PositiveSmallIntegerField(default=1)),
                ('iniciado_en', models.DateTimeField()),
                ('finalizado_en', models.DateTimeField(blank=True, null=True)),
                ('mensaje_error', models.TextField(blank=True, null=True)),
                ('ejecucion_original', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reintentos', to='app.ejecuciontareaprogramada')),
            ],
            options={
                'db_table': '[ml].[ejecucion_tarea_programada]',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FuenteDatosParametros',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(default=False)),
                ('clave', models.CharField(max_length=100)),
                ('valor', models.TextField()),
                ('tipo_dato', models.CharField(default='string', max_length=20)),
                ('fuente_datos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parametros', to='app.fuentedatos')),
            ],
            options={
                'db_table': '[ml].[fuente_datos_parametros]',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LogTareaProgramada',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(default=False)),
                ('nombre_step', models.CharField(max_length=100)),
                ('orden_step', models.PositiveSmallIntegerField()),
                ('estado', models.CharField(max_length=20)),
                ('duracion_segundos', models.FloatField(blank=True, null=True)),
                ('mensaje_error', models.TextField(blank=True, null=True)),
                ('ejecutado_en', models.DateTimeField()),
                ('ejecucion_tarea_programada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_steps', to='app.ejecuciontareaprogramada')),
            ],
            options={
                'db_table': '[ml].[log_tarea_programada]',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResultadoPrediccion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(default=False)),
                ('cliente_id', models.CharField(max_length=50)),
                ('producto_id', models.CharField(max_length=50)),
                ('fuente', models.CharField(max_length=20)),
                ('cantidad_sugerida', models.FloatField()),
                ('score', models.FloatField()),
                ('posicion', models.PositiveSmallIntegerField()),
                ('complementos', models.CharField(blank=True, max_length=500, null=True)),
                ('lote_prediccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='app.loteprediccion')),
            ],
            options={
                'db_table': '[ml].[resultado_prediccion]',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TareaProgramada',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(default=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('tipo_job', models.CharField(max_length=30)),
                ('cron_schedule', models.CharField(blank=True, max_length=50, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('max_reintentos', models.PositiveSmallIntegerField(default=0)),
                ('delay_reintento_segundos', models.PositiveIntegerField(default=300)),
                ('fuente_datos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fuente_datos_tarea', to='app.fuentedatos')),
            ],
            options={
                'db_table': '[ml].[tarea_programada]',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TareaParametro',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(default=False)),
                ('clave', models.CharField(max_length=100)),
                ('valor', models.CharField(max_length=500)),
                ('tipo_dato', models.CharField(default='string', max_length=20)),
                ('tarea_programada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parametros', to='app.tareaprogramada')),
            ],
            options={
                'db_table': '[ml].[tarea_parametro]',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='ejecuciontareaprogramada',
            name='tarea_programada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ejecuciones', to='app.tareaprogramada'),
        ),
        migrations.CreateModel(
            name='VersionModelo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('eliminado', models.BooleanField(default=False)),
                ('nombre_modelo', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=50)),
                ('entrenado_en', models.DateTimeField()),
                ('ruta_pkl', models.CharField(max_length=500)),
                ('parametros', models.JSONField(default=dict)),
                ('activo', models.BooleanField(default=False)),
                ('ejecucion_tarea_programada', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='version_modelo', to='app.ejecuciontareaprogramada')),
                ('fuente_datos', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fuente_datos_version', to='app.fuentedatos')),
            ],
            options={
                'db_table': '[ml].[version_modelo]',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='loteprediccion',
            name='version_modelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lote_prediccion_activo', to='app.versionmodelo'),
        ),
    ]
