# Generated by Django 5.2 on 2026-04-26 21:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_add_retry_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="Clientes",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("eliminado", models.BooleanField(default=False)),
                ("nombre_cliente", models.CharField(max_length=200)),
                ("codigo_erp", models.CharField(max_length=100)),
                ("registrado_en", models.DateTimeField()),
            ],
            options={
                "db_table": "[ml].[clientes]",
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="resultadoprediccion",
            name="complementos",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        ALTER TABLE [ml].[tarea_programada]
                        ADD delay_reintento_segundos int NOT NULL DEFAULT 300
                    """,
                    reverse_sql="""
                        ALTER TABLE [ml].[tarea_programada]
                        DROP COLUMN delay_reintento_segundos
                    """,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="tareaprogramada",
                    name="delay_reintento_segundos",
                    field=models.PositiveIntegerField(default=300),
                ),
            ],
        ),
    ]
