# Generated by Django 5.2 on 2026-04-26 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_clientes_resultadoprediccion_complementos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loteprediccion',
            name='nombre_modelo',
            field=models.CharField(max_length=100),
        ),
    ]
